# Site settings
encoding: "utf-8"
title: angularjs-requirejs-skeleton
email: leftstick@qq.com
description: A seed project can be forked for web-developer. You would learn how `angularjs` used for organizing complicated application
baseurl: "/angularjs-requirejs-skeleton"
url: "http://leftstick.github.io"

github_username:  leftstick
git_repository: https://github.com/leftstick/angularjs-requirejs-skeleton

# Build settings
markdown: redcarpet

highlighter: pygments

redcarpet:
  extensions: ["fenced_code_blocks"]
